"""add suggested_reply_status to tickets

Revision ID: 892286318f45
Revises: f3d190ca2609
Create Date: 2026-03-25 20:36:41.491043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '892286318f45'
down_revision: Union[str, Sequence[str], None] = 'f3d190ca2609'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('suggested_reply_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'suggested_reply_status')
    # ### end Alembic commands ###
