"""add suggested_reply to tickets

Revision ID: c88d8a8bc8b3
Revises: 832454d0de44
Create Date: 2026-03-25 19:28:42.486952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c88d8a8bc8b3'
down_revision: Union[str, Sequence[str], None] = '832454d0de44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('suggested_reply', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'suggested_reply')
    # ### end Alembic commands ###
